apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo8-1
  namespace: uptime-demo8-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---